// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetPriceLog = `-- name: CreateAssetPriceLog :one
insert into
    asset_price_logs (asset_id, price)
values
    ($1, $2)
returning id, asset_id, price, created_at
`

type CreateAssetPriceLogParams struct {
	AssetID pgtype.Int8
	Price   pgtype.Numeric
}

func (q *Queries) CreateAssetPriceLog(ctx context.Context, arg CreateAssetPriceLogParams) (AssetPriceLog, error) {
	row := q.db.QueryRow(ctx, createAssetPriceLog, arg.AssetID, arg.Price)
	var i AssetPriceLog
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const createOrUpdateAsset = `-- name: CreateOrUpdateAsset :one
insert into
    assets (code, price, updated_at)
values
    ($1, $2, $3)
on conflict (code)
    do update set
                  price      = excluded.price,
                  updated_at = excluded.updated_at
returning id, code, price, created_at, updated_at
`

type CreateOrUpdateAssetParams struct {
	Code      string
	Price     pgtype.Numeric
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateOrUpdateAsset(ctx context.Context, arg CreateOrUpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createOrUpdateAsset, arg.Code, arg.Price, arg.UpdatedAt)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
select id, code, price, created_at, updated_at
from
    assets
where
    code = $1
`

func (q *Queries) GetAsset(ctx context.Context, code string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, code)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetsWithPriceChanges = `-- name: ListAssetsWithPriceChanges :many
with
    price_changes_4h as (select distinct on (asset_id)
                             asset_id,
                             first_value(price)
                             over (partition by asset_id order by created_at range between unbounded preceding and unbounded following) as first,
                             last_value(price)
                             over (partition by asset_id order by created_at range between unbounded preceding and unbounded following) as last
                         from
                             asset_price_logs
                         where
                             created_at > now() - interval '4 hours'),
    price_changes_1d as (select distinct on (asset_id)
                             asset_id,
                             first_value(price)
                             over (partition by asset_id order by created_at range between unbounded preceding and unbounded following) as first,
                             last_value(price)
                             over (partition by asset_id order by created_at range between unbounded preceding and unbounded following) as last
                         from
                             asset_price_logs
                         where
                             created_at > now() - interval '1 day'),
    price_changes_7d as (select distinct on (asset_id)
                             asset_id,
                             first_value(price)
                             over (partition by asset_id order by created_at range between unbounded preceding and unbounded following) as first,
                             last_value(price)
                             over (partition by asset_id order by created_at range between unbounded preceding and unbounded following) as last
                         from
                             asset_price_logs
                         where
                             created_at > now() - interval '7 days')

select id, code, price, created_at, updated_at, first4h, change4h, first1d, change1d, first7d, change7d
from
    assets
        left join lateral (
        select
            price_changes_4h.first::numeric                           as first4h,
            (price_changes_4h.last - price_changes_4h.first)::numeric as change4h
        from
            price_changes_4h
        where
            asset_id = assets.id
        ) as pch4h on true

        left join lateral (
        select
            price_changes_1d.first::numeric                           as first1d,
            (price_changes_1d.last - price_changes_1d.first)::numeric as change1d
        from
            price_changes_1d
        where
            asset_id = assets.id
        ) as pch1d on true

        left join lateral (
        select
            price_changes_7d.first::numeric                           as first7d,
            (price_changes_7d.last - price_changes_7d.first)::numeric as change7d
        from
            price_changes_7d
        where
            asset_id = assets.id
        ) as pch7d on true
`

type ListAssetsWithPriceChangesRow struct {
	ID        int64
	Code      string
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	First4h   pgtype.Numeric
	Change4h  pgtype.Numeric
	First1d   pgtype.Numeric
	Change1d  pgtype.Numeric
	First7d   pgtype.Numeric
	Change7d  pgtype.Numeric
}

func (q *Queries) ListAssetsWithPriceChanges(ctx context.Context) ([]ListAssetsWithPriceChangesRow, error) {
	rows, err := q.db.Query(ctx, listAssetsWithPriceChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsWithPriceChangesRow
	for rows.Next() {
		var i ListAssetsWithPriceChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.First4h,
			&i.Change4h,
			&i.First1d,
			&i.Change1d,
			&i.First7d,
			&i.Change7d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
