// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
insert into
    assets (code, name, price)
values
    ($1, $2, $3)
returning id, code, name, price, created_at
`

type CreateAssetParams struct {
	Code  string
	Name  string
	Price pgtype.Numeric
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset, arg.Code, arg.Name, arg.Price)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const createAssetPriceLog = `-- name: CreateAssetPriceLog :one
insert into
    asset_price_logs (asset_id, price)
values
    ($1, $2)
returning id, asset_id, price, created_at
`

type CreateAssetPriceLogParams struct {
	AssetID pgtype.Int8
	Price   pgtype.Numeric
}

func (q *Queries) CreateAssetPriceLog(ctx context.Context, arg CreateAssetPriceLogParams) (AssetPriceLog, error) {
	row := q.db.QueryRow(ctx, createAssetPriceLog, arg.AssetID, arg.Price)
	var i AssetPriceLog
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
select id, code, name, price, created_at
from
    assets
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
