// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetPriceLog = `-- name: CreateAssetPriceLog :one
insert into
    asset_price_logs (asset_id, price)
values
    ($1, $2)
returning id, asset_id, price, created_at
`

type CreateAssetPriceLogParams struct {
	AssetID pgtype.Int8
	Price   pgtype.Numeric
}

func (q *Queries) CreateAssetPriceLog(ctx context.Context, arg CreateAssetPriceLogParams) (AssetPriceLog, error) {
	row := q.db.QueryRow(ctx, createAssetPriceLog, arg.AssetID, arg.Price)
	var i AssetPriceLog
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const createOrUpdateAsset = `-- name: CreateOrUpdateAsset :one
insert into
    assets (code, price, updated_at)
values
    ($1, $2, $3)
on conflict (code)
    do update set
                  price      = excluded.price,
                  updated_at = excluded.updated_at
returning id, code, price, created_at, updated_at
`

type CreateOrUpdateAssetParams struct {
	Code      string
	Price     pgtype.Numeric
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateOrUpdateAsset(ctx context.Context, arg CreateOrUpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createOrUpdateAsset, arg.Code, arg.Price, arg.UpdatedAt)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
select id, code, price, created_at, updated_at
from
    assets
where
    code = $1
`

func (q *Queries) GetAsset(ctx context.Context, code string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, code)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
select id, code, price, created_at, updated_at
from
    assets
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
