// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        int64
	Code      string
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AssetPriceLog struct {
	ID        int64
	AssetID   pgtype.Int8
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
